export const seatReservationTrain = {
  vehicleType: 'TRAIN',
  deckCoachIndex: 0,
  coachItems: [
    {
      id: '80',
      number: 'B10(501) - not touch',
      dimension: {
        w: 58,
        h: 10,
      },
      places: [
        {
          number: '153',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '151',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '154',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '152',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '48',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '37',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 15,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '52',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '58',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '71',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '73',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '72',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '78',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '31',
          state: 'ALLOCATED',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '33',
          state: 'RESTRICTED',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '32',
          state: 'SELECTED',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '55',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '57',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '56',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '54',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '45',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '47',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 21,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 0,
            z: 0,
          },
          rotation: 90,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'WINDOW_SEAT'],
          selected: false,
        },
        {
          number: '65',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '67',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '66',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '64',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '61',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '63',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '62',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '68',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '75',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '77',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '76',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '74',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
      ],
      serviceElements: [
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'DRIVER_AREA_FULL',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 12,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'STAIR_AREA',
          position: {
            x: 7,
            y: 4,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'WIFI',
          position: {
            x: 7,
            y: 1,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 22,
            y: 8,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          position: {
            x: 28,
            y: 8,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 9,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 37,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_PASSAGE',
          position: {
            x: 57,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
        {
          icon: 'PLAYGROUND_AREA',
          position: {
            x: 40,
            y: 4,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_WHEELCHAIR_AREA',
          position: {
            x: 28,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'SKI_AREA',
          position: {
            x: 13,
            y: 3,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'MULTI_FUNCTION_AREA',
          position: {
            x: 18,
            y: 3,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'EASY_ACCESS_AREA',
          position: {
            x: 22,
            y: 3,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'PRAM_AREA',
          position: {
            x: 33,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
      ],
      travelClass: ['FIRST', 'SECOND'],
      propertyIds: ['BICYCLE', 'WHEELCHAIR_ICON', 'ANY_SEAT'],
    },
    {
      id: '81',
      number: 'B10(501) - not touch',
      dimension: {
        w: 58,
        h: 10,
      },
      places: [
        {
          number: '153',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '151',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '154',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '152',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '48',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '15',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '17',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '16',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '14',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '13',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '18',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '25',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '27',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '26',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '24',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '23',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '28',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '37',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '52',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '58',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '71',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '73',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '72',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '78',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '38',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '55',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '57',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '56',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '54',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '45',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '47',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '44',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '65',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '67',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '66',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '64',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '61',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '63',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '62',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '68',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 49,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '75',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '77',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 51,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '74',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 55,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
      ],
      serviceElements: [
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 7,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 1,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'SILENCE_AREA_ICON',
          position: {
            x: 22,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 9,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 37,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_PASSAGE',
          position: {
            x: 57,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
        {
          icon: 'BUSINESS',
          position: {
            x: 34,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'BISTRO',
          position: {
            x: 34,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'RESTAURANT_ICON',
          position: {
            x: 40,
            y: 4,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
      ],
      travelClass: ['SECOND'],
      propertyIds: ['BICYCLE_HIGH', 'ANY_SEAT'],
    },
    {
      id: '82',
      number: 'B10(501) - not touch',
      dimension: {
        w: 46,
        h: 10,
      },
      places: [
        {
          number: '15',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '17',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '16',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '14',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '13',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '18',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '25',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '27',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '26',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '24',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '23',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '28',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '153',
          state: 'ALLOCATED',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '151',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '154',
          state: 'RESTRICTED',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '152',
          state: 'SELECTED',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '48',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '37',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '52',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '58',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '38',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '55',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '57',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '56',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '54',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '45',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '47',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '44',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
      ],
      serviceElements: [
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 7,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 1,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'COACH_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 22,
            y: 8,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 9,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
      ],
      travelClass: ['SECOND', 'FIRST'],
      propertyIds: ['BISTRO', 'FAMILY', 'ANY_SEAT', 'WHEELCHAIR_NO_SEAT', 'BICYCLE_ICON', 'PRAM'],
    },
    {
      id: '86',
      number: 'B10(501) - not touch',
      dimension: {
        w: 32,
        h: 10,
      },
      places: [],
      serviceElements: [],
      graphicElements: [
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
      ],
      travelClass: [],
      propertyIds: [],
    },
    {
      id: '843',
      number: 'B10(501) - not touch',
      dimension: {
        w: 46,
        h: 10,
      },
      places: [
        {
          number: '15',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '17',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '16',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '14',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '13',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '18',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '25',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '27',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '26',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '24',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '23',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '28',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '153',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '151',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['BICYCLE_LOW'],
          selected: false,
        },
        {
          number: '154',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '152',
          state: 'FREE',
          type: 'BICYCLE',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '48',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '37',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '52',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '58',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '38',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '55',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '57',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 38,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '56',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '54',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '45',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '47',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 2,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
        {
          number: '44',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 2,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: [],
          selected: false,
        },
      ],
      serviceElements: [
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 7,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'WHEELCHAIR_ICON',
          position: {
            x: 40,
            y: 2,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'BICYCLE_LOW_ICON',
          position: {
            x: 28,
            y: 1,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 22,
            y: 8,
            z: 0,
          },
          dimension: {
            w: 3,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          position: {
            x: 33,
            y: 9,
            z: 0,
          },
          dimension: {
            w: 4,
            h: 1,
          },
          rotation: 90,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE',
          position: {
            x: 37,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
      ],
      travelClass: ['SECOND', 'FIRST'],
      propertyIds: ['ANY_SEAT', 'BICYCLE_ICON', 'PRAM'],
    },
    {
      id: '185',
      number: 'B10(501) - not touch',
      dimension: {
        w: 40,
        h: 10,
      },
      places: [],
      serviceElements: [],
      graphicElements: [
        {
          icon: 'DRIVER_AREA_FULL',
          position: {
            x: 28,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 12,
            h: 10,
          },
          rotation: 180,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 0,
        },
      ],
      travelClass: [],
      propertyIds: [],
    },
  ],
};

export const seatReservationBus = {
  vehicleType: 'BUS',
  deckCoachIndex: 0,
  coachItems: [
    {
      id: '32801',
      number: 'WR6(501) - not touch',
      dimension: {
        w: 56,
        h: 10,
      },
      places: [
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 37,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '41',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 39,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '61',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 47,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '62',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 53,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '13',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '14',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 37,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 37,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 39,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 6,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 39,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 47,
            y: 6,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['AISLE_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 47,
            y: 8,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
        {
          number: '52',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 53,
            y: 8,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          remarkId: '',
          propertyIds: ['WINDOW_SEAT', 'TABLE'],
          selected: false,
        },
      ],
      serviceElements: [
        {
          icon: 'RESTAURANT_ICON',
          position: {
            x: 32,
            y: 3,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
        {
          icon: 'RESTAURANT_ICON',
          position: {
            x: 46,
            y: 3,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'DRIVER_AREA_FULL',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 6,
            h: 10,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 55,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1,
            h: 10,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 42,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 4,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 50,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 34,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 34,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 4,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 42,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 2,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE_RESTAURANT',
          position: {
            x: 50,
            y: 6,
            z: 0,
          },
          dimension: {
            w: 2,
            h: 4,
          },
          rotation: 0,
        },
      ],
      travelClass: ['SECOND'],
      propertyIds: ['RESTAURANT'],
    },
  ],
};
