/**
 * GENERATED BY AI
 *
 * Generates src/docs/assets/guide-keywords.json by scanning the Markdown guide files
 * of src/angular and src/angular-experimental.
 *
 * Keywords are explicitly declared inside each guide file using an HTML comment:
 *   <!-- keywords: foo, bar, baz -->
 *
 * Output structure:
 * {
 *   "angular": {
 *     "getting-started": ["foo", "bar", ...],
 *     "theming": [...]
 *   },
 *   "angular-experimental": { ... }
 * }
 *
 * The keys match the last segment of the guide route links defined in meta.ts
 * (e.g. "./guides/getting-started" → "getting-started").
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { basename, join } from 'path';
import { fileURLToPath } from 'url';

const root = fileURLToPath(new URL('../', import.meta.url));

type GuideKeywordsMap = Record<string, Record<string, string[]>>;

function toCamelCase(str: string): string {
  return str.toLowerCase().replace(/[-_\s]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ''));
}

/** Parse the <!-- keywords: ... --> comment from a Markdown source string. */
function parseKeywords(source: string): string[] {
  const match = source.match(/<!--\s*keywords\s*:\s*([\s\S]*?)-->/);
  if (!match) {
    return [];
  }
  return match[1]
    .split(',')
    .map((kw) => kw.trim().toLowerCase())
    .filter((kw) => kw.length > 0);
}

/** Derive the guide route key from the filename, e.g. "guide-getting-started.md" → "getting-started". */
function guideKey(filename: string): string {
  return basename(filename, '.md').replace(/^guide-/, '');
}

function generateForPackage(pkg: 'angular' | 'angular-experimental'): Record<string, string[]> {
  const pkgDir = join(root, 'src', pkg);
  const result: Record<string, string[]> = {};

  for (const entry of readdirSync(pkgDir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.startsWith('guide-') || !entry.name.endsWith('.md')) {
      continue;
    }

    const source = readFileSync(join(pkgDir, entry.name), 'utf-8');
    const keywords = parseKeywords(source);

    if (keywords.length > 0) {
      result[toCamelCase(guideKey(entry.name))] = keywords;
    }
  }

  return result;
}

const guideKeywordsMap: GuideKeywordsMap = {
  angular: generateForPackage('angular'),
  angularExperimental: generateForPackage('angular-experimental'),
};

const outputPath = join(root, 'src/docs/app/shared/guide-keywords.json');
writeFileSync(outputPath, JSON.stringify(guideKeywordsMap, null, 2), 'utf-8');
console.log(`Generated ${outputPath}`);
