/**
 * GENERATED BY AI
 *
 * Generates src/docs/assets/selector-map.json by scanning the TypeScript source files
 * of src/angular and src/angular-experimental.
 *
 * For each top-level module folder it collects:
 *  - @Directive / @Component selector values (element + attribute selectors starting with "sbb")
 *  - @Input alias values (both shorthand @Input('alias') and @Input({ alias: '...' })) starting with "sbb"
 *
 * Output structure:
 * {
 *   "angular": { "button": ["sbb-button", ...], ... },
 *   "angular-experimental": { ... }
 * }
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';

const root = fileURLToPath(new URL('../', import.meta.url));

type SelectorMap = Record<string, Record<string, string[]>>;

function toCamelCase(str: string): string {
  return str.toLowerCase().replace(/[-_\s]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ''));
}

/** Extract all sbb-relevant values from a @Directive/@Component selector string. */
function selectorsFromDecoratorValue(raw: string): string[] {
  const results: string[] = [];
  for (const part of raw.split(',')) {
    const trimmed = part.trim();
    // Element selector: sbb-foo
    const elementMatch = trimmed.match(/^(sbb-[a-z0-9-]+)/);
    if (elementMatch) {
      results.push(elementMatch[1]);
      continue;
    }
    // Attribute selector: [sbbFoo], [sbb-foo], input[sbbFoo], etc.
    const attributeMatch = trimmed.match(/\[(sbb[A-Za-z0-9-]+)]/);
    if (attributeMatch) {
      results.push(attributeMatch[1]);
    }
  }
  return results;
}

/** Extract all sbb-relevant @Input alias values from a TypeScript source string. */
function inputAliasesFromSource(source: string): string[] {
  const results: string[] = [];

  // @Input('sbb-foo') or @Input("sbb-foo")
  for (const m of source.matchAll(/@Input\(\s*['"]([^'"]+)['"]\s*\)/g)) {
    if (m[1].startsWith('sbb')) {
      results.push(m[1]);
    }
  }

  // @Input({ alias: 'sbb-foo' }) or @Input({ alias: "sbb-foo" })
  for (const m of source.matchAll(/@Input\s*\(\s*\{[^}]*alias\s*:\s*['"]([^'"]+)['"]/g)) {
    if (m[1].startsWith('sbb')) {
      results.push(m[1]);
    }
  }

  return results;
}

/** Extract @Directive/@Component selector strings from a TypeScript source string.
 *  Skips decorators that are preceded by a JSDoc comment containing @internal.
 */
function directiveSelectorsFromSource(source: string): string[] {
  const results: string[] = [];

  // Match optional JSDoc comment + @Directive/@Component({ selector: '...' })
  for (const m of source.matchAll(
    /(\/\*\*[\s\S]*?\*\/\s*)?@(?:Directive|Component)\s*\(\s*\{[^}]*?selector\s*:\s*([`'"])([\s\S]*?)\2/g,
  )) {
    const jsdoc = m[1] ?? '';
    if (jsdoc.includes('@internal')) {
      continue;
    }
    results.push(...selectorsFromDecoratorValue(m[3]));
  }

  return results;
}

/** Recursively collect all .ts files (excluding .spec.ts) under a directory. */
function collectTsFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      files.push(...collectTsFiles(join(dir, entry.name)));
    } else if (entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.spec.ts')) {
      files.push(join(dir, entry.name));
    }
  }
  return files;
}

function generateForPackage(pkg: 'angular' | 'angular-experimental'): Record<string, string[]> {
  const pkgDir = join(root, 'src', pkg);
  const result: Record<string, string[]> = {};

  for (const entry of readdirSync(pkgDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }
    const module = entry.name;
    const moduleDir = join(pkgDir, module);
    const selectors = new Set<string>();

    for (const file of collectTsFiles(moduleDir)) {
      const source = readFileSync(file, 'utf-8');
      for (const s of directiveSelectorsFromSource(source)) {
        selectors.add(s);
      }
      for (const s of inputAliasesFromSource(source)) {
        selectors.add(s);
      }
    }

    if (selectors.size > 0) {
      result[toCamelCase(module)] = [...selectors].sort();
    }
  }

  return result;
}

const selectorMap: SelectorMap = {
  angular: generateForPackage('angular'),
  angularExperimental: generateForPackage('angular-experimental'),
};

const outputPath = join(root, 'src/docs/app/shared/selector-map.json');
writeFileSync(outputPath, JSON.stringify(selectorMap, null, 2), 'utf-8');
console.log(`Generated ${outputPath}`);
