name: Continuous Integration Requested
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [requested]

env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0] != null && github.event.workflow_run.pull_requests[0].number || '' }}

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: "Add 'preview-available' label"
        if: env.PR_NUMBER != ''
        # This label is used for filtering deployments in ArgoCD.
        # At the start of the Continuous Integration workflow, we remove the container available labels
        # which will be re-added after the Continuous Integration Secure workflow.
        run: |
          gh issue edit $PR_NUMBER --remove-label "preview-available"
          gh issue edit $PR_NUMBER --remove-label "diff-available"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
